
CREATE VIEW [dbo].[GongCountyMapping]
AS
SELECT
	CASE Id
	WHEN 8 THEN 1 --Meðimurska
	WHEN 16 THEN 1 -- Varaždinska
	WHEN 18 THEN 1 -- Krapinsko-zagorska
	WHEN 11 THEN 1 --KOPRIVNIÈKO-KRIŽEVAÈKA ŽUPANIJA
	WHEN 2 THEN 2 -- GRAD ZAGREB
	WHEN 22 THEN 2 -- inozemstvo
	WHEN 14 THEN 3 --VUKOVARSKO-SRIJEMSKA ŽUPANIJA
	WHEN 3 THEN 3 -- OSJEÈKO-BARANJSKA ŽUPANIJA
	WHEN 21 THEN 3 -- VIROVITIÈKO-PODRAVSKA ŽUPANIJA
	WHEN 19 THEN 3 --POŽEŠKO-SLAVONSKA ŽUPANIJA
	WHEN 20 THEN 3 --BRODSKO POSAVSKA
	WHEN 5 THEN 4 --BJELOVARSKO-BILOGORSKA ŽUPANIJA
	WHEN 1 THEN 4 --ZAGREBAÈKA ŽUPANIJA
	WHEN 12 THEN 4 --SISAÈKO-MOSLAVAÈKA ŽUPANIJA
	WHEN 17 THEN 4 --KARLOVAÈKA ŽUPANIJA
	WHEN 7 THEN 5 --PRIMORSKO-GORANSKA ŽUPANIJA
	WHEN 6 THEN 5 --ISTARSKA ŽUPANIJA
	WHEN 13 THEN 5 --LIÈKO-SENJSKA ŽUPANIJA
	WHEN 4 THEN 6 --ZADARSKA ŽUPANIJA
	WHEN 9 THEN 6 --ŠIBENSKO-KNINSKA ŽUPANIJA
	WHEN 15 THEN 6 --SPLITSKO-DALMATINSKA ŽUPANIJA
	WHEN 10 THEN 6 --DUBROVAÈKO-NERETVANSKA ŽUPANIJA
	END AS GongConstituencyNumber,
	Id AS CountyId,
	Name AS CountyName,
	Code AS CountyCode
FROM
	dbo.Counties
GO



